language: c

sudo: false

addons:
  apt:
    packages:
      - ccache
      - doxygen
      - graphviz

env:
  global:
    - CCACHE_CPP2=yes
  matrix:
    - 
    - COVERAGE=ON

before_install:
 - if [[ ${COVERAGE}  ]]; then pip install --user codecov; export CC="${CC} --coverage"; fi 

script:
  - ./benchmark.sh -v -N 1000
  - ./mdlj -h
  - ./mdlj -dpd 1.0 
  - ./mdlj -sd 1.0 -icf 0.xyz
  - ./mdlj -dpd 1.0 -rvl 1.3
  - ./mdlj -dpd 1.0 -rlc 1.3
  - ./mdlj -dpd 1.0 -rvl 1.3 -rlc 1.3
  - make doc 

after_success:
  - if [[ ${COVERAGE} ]]; then codecov -F ${CC% *}; fi
  - if [[ ${TRAVIS_JOB_NUMBER} = *.1 ]]; then
      git fetch origin gh-pages && git checkout -b gh-pages FETCH_HEAD;
      mv html/* .; rmdir html;
      git add --all .;
      if [[ ${TRAVIS_BRANCH} = master && ${encrypted_3d28ce244718_key} && ${encrypted_3d28ce244718_iv} && ${TRAVIS_PULL_REQUEST} == false ]]; then
        git config --global user.name "Automatic Deployment (Travis CI)";
        git config --global user.email "junghans@votca.org";
        git commit -m "Documentation Update";
        openssl aes-256-cbc -K $encrypted_3d28ce244718_key -iv $encrypted_3d28ce244718_iv -in deploy.enc -out ~/.ssh/id_rsa -d;
        chmod 600 ~/.ssh/id_rsa;
        git push git@github.com:${TRAVIS_REPO_SLUG} gh-pages:gh-pages;
      else
        git status;
        git diff --cached --no-color | head -n 500;
      fi;
    fi

cache:
  - ccache

compiler:
  - clang
  - gcc
