language: c

sudo: false

addons:
  apt:
    packages:
      - ccache

env:
  global:
    - CCACHE_CPP2=yes
  matrix:
    - 
    - COVERAGE=ON

before_install:
 - if [[ ${COVERAGE}  ]]; then pip install --user codecov; export CC="${CC} --coverage"; fi 

script:
  - ./benchmark.sh -v -N 1000
  - ./mdlj -h
  - ./mdlj -dpd 1.0 
  - ./mdlj -sd 1.0 -icf 0.xyz
  - ./mdlj -dpd 1.0 -rvl 1.3
  - ./mdlj -dpd 1.0 -rlc 1.3
  - ./mdlj -dpd 1.0 -rvl 1.3 -rlc 1.3

after_success:
  - if [[ ${COVERAGE} ]]; then PATH=/usr/bin find . -type f -name "*.gcno" -execdir gcov {} + &>/dev/null && codecov; fi

cache:
  - ccache

compiler:
  - clang
  - gcc
